### ISSUE TITLE
support webpack v5

### ISSUE THREAD

**Issue by aladdin-add** [webpack-contrib/thread-loader#84]

**Comment by kirill-konshin** [comment]
Is this plugin even required for Webpack 5?

**Comment by kirill-konshin** [comment]
@sokra can you please suggest if `thread-loader` is useful for Webpack 5 or it can be skipped?

**Comment by sokra** [comment]
Still useful

**Comment by kirill-konshin** [comment]
@sokra thank you for clarification. Is there any way I can help to have this fixed, @mistic, any suggestions where to dig?

**Comment by evilebottnawi** [comment]
@kirill-konshin Just run thread-loader using webpack and catch all bugs

**Comment by kirill-konshin** [comment]
@evilebottnawi:
> @kirill-konshin Just run thread-loader using webpack and catch all bugs

I decided to update all versions of plugins and webpack, and now I can't reproduce anymore, because I can't find what versions were used before... :) lessons learned: always dump error message into the issue ASAP, as you may never see it again.

The only thing that I've observed is `<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: EBUSY: archive closed, lstat '/node_modules/thread-loader/dist/workerPools.js'`, but this may also fail because I'm using Yarn 2 with PNP, and there's no `node_modules`. I guess it has to be a separate bug?

Versions:
- thread-loader: 2.1.3
- webpack: 5.0.0-beta.22

**Comment by evilebottnawi** [comment]
@kirill-konshin Oh, looks this loader doesn't have compatibility with webpack@5 cache, but it is very weird, can you create reproducible test repo?

**Comment by kirill-konshin** [comment]
@evilebottnawi looks like it's something else: `<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: EBUSY: archive closed, lstat '/node_modules/ajv-keywords'` now... and I can't reproduce it in isolated repo, yet.

**Comment by aladdin-add** [comment]
I was using `"webpack": "^5.0.0-beta.22"` with the plugin, and it seems working fine. 🎉

**Comment by evilebottnawi** [comment]
@kirill-konshin Very weird, Maybe you can provide more information?

**Comment by kirill-konshin** [comment]
@evilebottnawi I was trying to reproduce it in separate project in isolated env, but I can't make it spit this error. I will keep trying various options.

**Comment by evilebottnawi** [comment]
@kirill-konshin feel free to ping me, because I can't reproduce too :disappointed:

**Comment by kirill-konshin** [comment]
I have upgraded all Babel and Webpack plugins & presets, and the issue is now gone. And I cannot reproduce it in isolated env too. Maybe it was just a side effect of the combination of libs. I guess we can close this issue.

**Comment by evilebottnawi** [comment]
@kirill-konshin let's keep open for a while, I will close this after we do new major release (fixes with `getResolve`/ minimum Node.js is 10.13 and etc)
